### ISSUE TITLE
anyone here?

### ISSUE THREAD

**Issue by scottfrederick** [vertx/VsBuilder#1]
There is an open-source project hosted on GitHub named [vert.x](http://vertx.io) (https://github.com/purplefox/vert.x). It is currently one of the most watched and followed projects on GitHub. The community would like to create a GitHub organization around this project, and "vertx" is the most natural name for the organization.  Since this account doesn't seem to have much activity, would you be willing to relinquish the "vertx" name so the vert.x project can use it?

We have considered other names for the GitHub organization, but anything else will likely cause confusion. 

Thanks for your consideration.

**Comment by RowanKaag** [comment]
bump
